apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: jeevn-git-app
  namespace: argocd
spec:
  project: default
  source:
    directory:
      recurse: true
    repoURL: https://github.com/jeevaratnamputla/argo-cd.git
    targetRevision: main
    path: applicationset/generators/git-generator/
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
