apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jeevan-merge-generator
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - merge:
        generators:
          # Git Generator - Fetching repositories from Git
          - git:
              repoURL: "https://github.com/jeevaratnamputla/argo-cd.git"
              revision: "main"
              files:
                - path: "applicationset/data/cm"
                - path: "applicationset/data/pod"
          # List Generator - Static list of parameters
          - list:
              elements:
                - name: "jeevan-list-cm"
                  repoURL: "https://github.com/jeevaratnamputla/argo-cd.git"
                  targetRevision: main
                  path: "applicationset/data/cm"
                - name: "jeevan-list-pod"
                  repoURL: "https://github.com/jeevaratnamputla/argo-cd.git"
                  targetRevision: main
                  path: "applicationset/data/pod"
  template:
    metadata:
      name: '{{.name}}-application'  # Dynamic application name based on the generator name
    spec:
      project: default  # Specify the Argo CD project
      source:
        repoURL: '{{.repoURL}}'  # Dynamically set the source repo URL
        targetRevision: '{{.targetRevision}}'  # Dynamically set the branch name
        path: '{{.path}}'  # Dynamically set the path
      destination:
        server: https://kubernetes.default.svc  # Set the Kubernetes server
        namespace: '{{.name}}'  # Dynamic namespace based on application name
