apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jeevan-list-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: list-applicationset-app1
            repoURL: https://github.com/jeevaratnamputla/argo-cd.git          #pod
            targetRevision: main
            path: applicationset/data
      - list:
        elements:
          - name: list-applicationset-app2
            repoURL: https://github.com/jeevaratnamputla/argo-workflows.git         
            targetRevision: main
            path: guestbook
  template:
    metadata:
      name: '{{name}}'
      labels:
        for: cnoe
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
