apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jeevan-git-generator-file
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/jeevaratnamputla/argo-cd.git
        revision: HEAD
        files:
        - path: "applicationset/data/cm/cm.yaml"
  template:
    metadata:
      name: '{{.cluster.name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/jeevaratnamputla/argo-cd.git
        targetRevision: HEAD
        path: "applicationset/data/cm"
      destination:
        server: https://kubernetes.default.svc
        #server: '{{.cluster.address}}'
        namespace: japplicationset
