# this generator i use for one git source and one helm source
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jeevan-git-generator
  namespace: argocd
spec:
  generators:
    - git:                 
        repoURL: "https://github.com/jeevaratnamputla/argo-cd.git"
        revision: "main"
        directories:
          - path: "applicationset/data"
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
         for: cnoe
    spec:
      project: default
      source:
        repoURL: "https://github.com/jeevaratnamputla/argo-cd.git"
        targetRevision: "main"
        path: '{{path}}'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: 'japplicationset'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
