apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jeevan-matrix-generator
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:                 
             repoURL: "https://github.com/jeevaratnamputla/argo-cd.git"             #cm
             revision: "main"
             directories:
               - path: "applicationset/data/cm" 
               - path: "applicationset/data/pod"               #pod
          # list generator, 'child' #2
          - list:
              elements:
                # - name: matrix-applicationset-app1
                  # repoURL: https://github.com/jeevaratnamputla/argo-cd.git          
                  # targetRevision: main
                  # path: applicationset/data
                  namespace: j-applicationset
  template:
    metadata:
      name: '{{.path.basename}}-{{.name}}'  # Combine path basename and name for unique app names
    spec:
      project: default  # Default Argo CD project
      source:
        repoURL: https://github.com/jeevaratnamputla/argo-cd.git  # Same repo for all applications
        targetRevision: main
        path: '{{.path.path}}'  # Use the dynamic path from the git generator
      destination:
        server: '{{.server}}'  # Dynamic server from list generator
        namespace: '{{.namespace}}'  # Dynamic namespace from list generator
