# this generator i use for one git source and one helm source
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-application-set
  namespace: argocd
spec:
  generators:
    - git:                 
        repoURL: "https://github.com/OpsMx/argo-customer-demo.git"
        revision: "testcase"
        directories:
          - path: "source-data/application-set-data/git-data/*"
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
         for: jpmc
    spec:
      project: default
      source:
        repoURL: "https://github.com/OpsMx/argo-customer-demo.git"
        targetRevision: "testcase"
        path: '{{path}}'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: 'argocd-kt'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
